### ISSUE TITLE
Crash related to Oh The Trees You'll Grow

### ISSUE THREAD

**Issue by MayD2099** [Darsenia/woodlands#1]
[crash-2024-11-11_22.22.42-server.txt](https://github.com/user-attachments/files/17757864/crash-2024-11-11_22.22.42-server.txt)

**Comment by Darsenia** [comment]
Thanks for the feedback! That's a known issue, unfortunately, it happenes when a beehive generates on a tree, added by a datapack. This could happen if a vanilla tree is added via datapack, so it also could be some kind of Minecraft's datapack-related issue. CorgiTaco is aware of it too.
It could happen ocassionally and is impossible to know in advance.
I already removed beehives from the cherry trees a few days ago and updated the mods, and I hope this issue will be gone ;) 

#https://github.com/CorgiTaco/Oh-The-Trees-Youll-Grow/issues/11
